import { createContext, useContext, useState, useEffect } from "react";

const AppContext = createContext();

export const translations = {
  en: {
    appName: "ChillerLoop",
    tagline: "Navi Mumbai's Underground Cooling Intelligence",
    dashboard: "Dashboard",
    flowTracker: "Flow Speed Tracker",
    compressor: "Compressor Override",
    restartQueue: "Emergency Restart Queue",
    equipmentChecker: "Equipment ID Checker",
    heatSorter: "Heat Load Sorter",
    pipeMap: "Pipe Map Hub",
    flowPlanner: "Efficient Flow Planner",
    fanBalancer: "Fan Power Balancer",
    excelReport: "Excel Reports",
    about: "About",
    settings: "Settings",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    search: "Search...",
    status: "Status",
    active: "Active",
    inactive: "Inactive",
    critical: "Critical",
    normal: "Normal",
    warning: "Warning",
    apply: "Apply",
    undo: "Undo",
    verify: "Verify",
    restart: "Restart",
    sort: "Sort by Heat Load",
    calculate: "Calculate Path",
    balance: "Balance Load",
    pressure: "Pressure (bar)",
    flowRate: "Flow Rate (L/s)",
    temperature: "Temperature (°C)",
    power: "Power (kW)",
    zone: "Zone",
    priority: "Priority",
    high: "High",
    medium: "Medium",
    low: "Low",
    assetId: "Asset ID",
    checkId: "Check ID",
    valid: "Valid ✓",
    invalid: "Invalid ✗",
    enterAssetId: "Enter Asset ID",
    nodes: "Nodes",
    path: "Optimal Path",
    energySaved: "Energy Saved",
    loadPercent: "Load %",
    fan: "Fan",
    distribute: "Distribute Evenly",
  },
  
  hi: {
    appName: "चिलरलूप",
    tagline: "नवी मुंबई का भूमिगत शीतलन तंत्र",
    dashboard: "डैशबोर्ड",
    flowTracker: "प्रवाह गति ट्रैकर",
    compressor: "कंप्रेसर ओवरराइड",
    restartQueue: "आपातकालीन पुनः आरंभ कतार",
    equipmentChecker: "उपकरण आईडी जाँचकर्ता",
    heatSorter: "ऊष्मा लोड सॉर्टर",
    pipeMap: "पाइप मानचित्र केंद्र",
    flowPlanner: "कुशल प्रवाह योजनाकार",
    fanBalancer: "पंखा शक्ति संतुलनकर्ता",
    excelReport: "एक्सेल रिपोर्ट",
    about: "परिचय",
    settings: "सेटिंग्स",
    language: "भाषा",
    theme: "थीम",
    light: "हल्का",
    dark: "गहरा",
    search: "खोजें...",
    status: "स्थिति",
    active: "सक्रिय",
    inactive: "निष्क्रिय",
    critical: "गंभीर",
    normal: "सामान्य",
    warning: "चेतावनी",
    apply: "लागू करें",
    undo: "पूर्ववत करें",
    verify: "सत्यापित करें",
    restart: "पुनः आरंभ",
    sort: "ऊष्मा लोड से क्रमबद्ध करें",
    calculate: "मार्ग की गणना करें",
    balance: "लोड संतुलित करें",
    pressure: "दबाव (बार)",
    flowRate: "प्रवाह दर (L/s)",
    temperature: "तापमान (°C)",
    power: "शक्ति (kW)",
    zone: "क्षेत्र",
    priority: "प्राथमिकता",
    high: "उच्च",
    medium: "मध्यम",
    low: "निम्न",
    assetId: "संपत्ति आईडी",
    checkId: "आईडी जाँचें",
    valid: "मान्य ✓",
    invalid: "अमान्य ✗",
    enterAssetId: "संपत्ति आईडी दर्ज करें",
    nodes: "नोड्स",
    path: "इष्टतम मार्ग",
    energySaved: "ऊर्जा बचत",
    loadPercent: "लोड %",
    fan: "पंखा",
    distribute: "समान रूप से वितरित करें",
  },
  
  mr: {
    appName: "चिलरलूप",
    tagline: "नवी मुंबईची भूमिगत शीतकरण प्रणाली",
    dashboard: "डॅशबोर्ड",
    flowTracker: "प्रवाह गती ट्रॅकर",
    compressor: "कंप्रेसर ओव्हरराइड",
    restartQueue: "आपत्कालीन पुनः प्रारंभ रांग",
    equipmentChecker: "उपकरण आयडी तपासक",
    heatSorter: "उष्णता लोड क्रमवारी",
    pipeMap: "पाइप नकाशा केंद्र",
    flowPlanner: "कार्यक्षम प्रवाह नियोजक",
    fanBalancer: "पंखा ऊर्जा संतुलक",
    excelReport: "एक्सेल अहवाल",
    about: "परिचय",
    settings: "सेटिंग्ज",
    language: "भाषा",
    theme: "थीम",
    light: "उजळ",
    dark: "गडद",
    search: "शोधा...",
    status: "स्थिती",
    active: "सक्रिय",
    inactive: "निष्क्रिय",
    critical: "गंभीर",
    normal: "सामान्य",
    warning: "इशारा",
    apply: "लागू करा",
    undo: "पूर्ववत करा",
    verify: "सत्यापित करा",
    restart: "पुनः सुरू करा",
    sort: "उष्णता लोडनुसार क्रमवारी",
    calculate: "मार्ग मोजा",
    balance: "लोड संतुलित करा",
    pressure: "दाब (बार)",
    flowRate: "प्रवाह दर (L/s)",
    temperature: "तापमान (°C)",
    power: "ऊर्जा (kW)",
    zone: "क्षेत्र",
    priority: "प्राधान्य",
    high: "उच्च",
    medium: "मध्यम",
    low: "निम्न",
    assetId: "मालमत्ता आयडी",
    checkId: "आयडी तपासा",
    valid: "वैध ✓",
    invalid: "अवैध ✗",
    enterAssetId: "मालमत्ता आयडी प्रविष्ट करा",
    nodes: "नोड्स",
    path: "इष्टतम मार्ग",
    energySaved: "ऊर्जा बचत",
    loadPercent: "लोड %",
    fan: "पंखा",
    distribute: "समान वाटप करा",
  },
};

export function AppProvider({ children }) {
  const [theme, setTheme] = useState("dark");
  const [lang, setLang] = useState("en");
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [activePage, setActivePage] = useState("dashboard");

  const t = translations[lang];

  useEffect(() => {
    document.documentElement.setAttribute("data-theme", theme);
  }, [theme]);

  return (
    <AppContext.Provider value={{ theme, setTheme, lang, setLang, t, sidebarOpen, setSidebarOpen, activePage, setActivePage }}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  return useContext(AppContext);
}
